version: '3.8'
services:
  prod:
    container_name: auth-prod
    image: auth:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: yarn start:prod
    volumes:
      - .:/usr/src/auth
    restart: unless-stopped